### ISSUE TITLE
not an issue just suggesting

### ISSUE THREAD

**Issue by Makuru-DD** [mayankmetha/Rucky#10]
Make an autostart if possible that when I put it in an USB Port it starts

**Comment by mayankmetha** [comment]
This may depend on kernel/ROM support. To provide uniform support across various devices this feature won’t be supported soon via the Rucky App.

**Comment by mayankmetha** [comment]
App auto start on USB will not be implemented, but USB auto attack launch can be set via a settings from the next release.
