### ISSUE TITLE
Support for Swiss Keyboard Layout

### ISSUE THREAD

**Issue by rdtm443** [mayankmetha/Rucky#113]
Hey there

First of all, thanks for this wonderful project :)

Second, I'd love to have the option to choose swiss keyboard layout. Is there any chance that this will be included in future updates? Or can additional layouts somehow be imported to the app manually?

Thanks a lot!

Best

**Comment by mayankmetha** [comment]
You can make use of HID Customisation option in settings and add the Swiss keyboard manually. You can also submit the key details to  https://github.com/mayankmetha/Rucky-KeyMap

**Comment by Maxsteff57** [comment]
Hi, nice prog!
Is it possible to introduce alt codes and delay in a custom HID configuration (Keymap) ? I really need it.

By the way, I made a configuration for Russian and English.
I attach the file ;)

[LANG.json.zip](https://github.com/mayankmetha/Rucky/files/11003607/LANG.json.zip)

**Comment by mayankmetha** [comment]
@Maxsteff57 alt and delay commands are already present.

HID configuration can be submitted as pull request to https://github.com/mayankmetha/Rucky-KeyMap

**Comment by Maxsteff57** [comment]
Sorry, I didn't really understand
How can I enter unicode characters?
