### ISSUE TITLE
Key '|' is incorect configured in german keyboard layout 

### ISSUE THREAD

**Issue by Herolias** [mayankmetha/Rucky#13]
The Key | is written as < in cmd.exe . This makes it imposible to run playloads like Wifi Password Grabber

**Comment by mayankmetha** [comment]
Can you specify the details as mentioned below
Type: Missing/Correction
Keyboard Language:
Unicode Value: \u
Encoding: ASCII/ISO_8859-1/ISO_8859-5/Unicode
Shift Used: T/F
Meta/Windows Used: T/F
Alt Used: T/F
Ctrl Used: T/F

**Comment by mayankmetha** [comment]
@Herolias haven't heard from you lately. Do you mind providing the details as provided above so that the bug can be resolved, else I have to think this is a false bug report and close the issue.

**Comment by mayankmetha** [comment]
Closing issue due to lack of input
