### ISSUE TITLE
STRINGLN bug

### ISSUE THREAD

**Issue by Rayrsn** [mayankmetha/Rucky#144]
When I add a `STRINGLN` in my script it types out the whole line.
for example, running the following script:
```ducky
STRING Hello
ENTER
STRINGLN World
```

will result in

```
Hello
STRINGLN World
```

Using version `Nightly 2.3` on Android 12

**Comment by mayankmetha** [comment]
Stringln is part of rubber ducky 3.0 which is not part of nightly builds yet. Nightly build only support upto rubber ducky 2.0 scripts.
