### ISSUE TITLE
How to install a custom kernel?

### ISSUE THREAD

**Issue by Kiriox94** [mayankmetha/Rucky#150]
Hello, I wanted to try your application with a USB attack (my phone is rooted) but I can't understand what you call custom kernel and how to install it, do you have a tutorial?

**Comment by eersya** [comment]
Hi! You need to find the kernel sources of your device, try to compile a couple of times, you can find good guides in XDA. Then, when you're comfortable with compiling, apply the modules that enable HID support https://www.kali.org/docs/nethunter/nethunter-kernel-7-config-6/

**Comment by Kiriox94** [comment]
> Salut! Vous devez trouver les sources du noyau de votre périphérique, essayez de compiler plusieurs fois, vous pouvez trouver de bons guides dans XDA. Ensuite, lorsque vous êtes à l’aise avec la compilation, appliquez les modules qui permettent la prise en charge HID https://www.kali.org/docs/nethunter/nethunter-kernel-7-config-6/

Thanks for your response, but am I required to compile it myself can't I use one that has already been compiled?

**Comment by Kiriox94** [comment]
And what will happen if I install a custom kernel will it just allow rucky to attack or will it really modify my system?

**Comment by Rayrsn** [comment]
In my case i didn't have to install a new kernel because my kernel had configfs support, you can check if your kernel has the support by installing [android-usb-gadget](https://github.com/tejado/android-usb-gadget/releases), and going to the device info

**Comment by Kiriox94** [comment]
> Dans mon cas, je n’ai pas eu besoin d’installer un nouveau noyau car mon noyau avait le support configfs, vous pouvez vérifier si votre noyau a le support en installant [android-usb-gadget](https://github.com/tejado/android-usb-gadget/releases), et en allant dans les informations sur le périphérique

I installed it but in device info there are lots of options, which one will tell me if my phone is compatible or not?

**Comment by Rayrsn** [comment]
the `CONFIG_USB_CONFIGFS_F_HID` one

**Comment by Kiriox94** [comment]
It's marked Yes yet rucky tells me that my kernel is not supported, is there anything else to do?

**Comment by Rayrsn** [comment]
in usb gadget press the plus button on the top and tap on `mouse and keyboard` and try again

**Comment by Kiriox94** [comment]
No it doesn't change anything

**Comment by mayankmetha** [comment]
Either your device needs to be above linux kernel 3.14 for configfs to enable hid or you need to use kernel with usb hid drivers
