### ISSUE TITLE
Suggestion: Adding the feature to import different keymaps

### ISSUE THREAD

**Issue by bojtalepenye** [mayankmetha/Rucky#151]
## Little background story:
I managed to root my phone and configure ConfigFS on my device, so I am able to use the Rucky app. However I have noticed that because my devcies' (Laptops/PCs) keyboards are set to HU (Hungarian), and Rucky only has US or UK keyboard layout, I am not able to get it's full capability.
## Issue:
There is no way to import costum keyboard layouts. So I always have to switch layouts on my devices. Maybe there is a way, but I just don't know about it. Exactly where are these layouts/keymaps located at. I am assuming these are .json files. So there must be a way to import them. I would greately appreciate if someone explained this to me. :)) I also want to know where the files are saved, when I save a file.

Apart from these issues, I absolutely love the app; Amazing work

**Comment by mayankmetha** [comment]
Feature already present.
