### ISSUE TITLE
Virtual environment not supported on real hardware 

### ISSUE THREAD

**Issue by srt54558** [mayankmetha/Rucky#153]
Hello,
I know that this issue has been posted before, but it got closed.

My Google pixel 8 pro does indeed work with v2.2 but the newest version says "virtual environment not supported". I am on Stock OS and rooted

Android 14 QPR2/ March update / stable

Can you remove this check, because people in virtual environments should know that this app doesn't work anyway?

**Comment by mayankmetha** [comment]
Please check OS flags as on of them is triggering this. Alternate is to use custom ROM. These configurations are beyond the APP's scope.

Config is required as APP requires real HW to work on not on emulators.

**Comment by srt54558** [comment]
> Please check OS flags as on of them is triggering this. Alternate is to use custom ROM. These configurations are beyond the APP's scope.
> 
> Config is required as APP requires real HW to work on not on emulators. 

Then every single Google pixel doesn't work. The Google pixel stock ROM has these flags (and the app works).
