### ISSUE TITLE
Rrr

### ISSUE THREAD

**Issue by anzor124** [mayankmetha/Rucky#18]
Type: Missing/Correction
Keyboard Language:
Unicode Value: \u
Encoding: ASCII/ISO_8859-1/ISO_8859-5/Unicode
Shift Used: T/F
Meta/Windows Used: T/F
Alt Used: T/F
Ctrl Used: T/F

**Comment by mayankmetha** [comment]
Spam issue. @anzor124 you have been reported for spamming.
