### ISSUE TITLE
Cursor color issue

### ISSUE THREAD

**Issue by AmmarXelcoder** [mayankmetha/Rucky#19]
While using the app and trying to edit the script using the editor there 
The cursor color is the same as the background so I can't see where am I typing 
I wish u fix it soon to make the app 100% perfect
Thx in advance

**Comment by AmmarXelcoder** [comment]
I saw the already closed issue but if it has returned back in the last update

**Comment by mayankmetha** [comment]
This issue has been fixed and will be shipped with next update. Just waiting for android 11 APIs to be finalised so I can check and fix the issues that could arise.
