### ISSUE TITLE
Dependency file missing

### ISSUE THREAD

**Issue by Loki029** [mayankmetha/Rucky#2]
When opened, notification that Dependency file is missing pops up. Two possible options aviable: Exit or Download and Install

Exit works fine ;)
But the App crashes by Download and Install.

I tried to reinstall, check if I granted root acess properly, checked latest version, checked if my device caused any errors (due to a device changer), but I can't find the problem.

P.m. if you need the logs

In kind Regards,
.

**Comment by mayankmetha** [comment]
Sure send me the logs. I’ll try to fix this issue ASAP.

**Comment by Loki029** [comment]
The Crash isn't happening anymore and I couldn't recreate the crash, the latest complete delete also deleted the logs from before (should have been obvious, but I forgot to save them seperatly).

After the third reinstall and checking the permissions in root Browser it seemed to work. Unluckily my kernel isn't supported....

If there is a Way to get Rucky working, please leave a short Reply. I'm willing to sacrifice my time to get it working, always afraid my Malduino Elite breaks without a Case :')

Still thank you for your fast response and the Help you offered.

In kind Regards


P.S.: If there is no way, I will use one of my Burner Phones to get it working :"(
