### ISSUE TITLE
STRING command do starnge things

### ISSUE THREAD

**Issue by SM-py** [mayankmetha/Rucky#24]
I tested Rucky on Kali Linux and commands like CTRL ALT T work as well. But if i need input text comand STRING do starnge things, for example if i execute comands:
CTRL ALT T
DELAY 200
STRING lol
opens new terminal window and Rucky input here  "lsls@s@s@s@s" .
If I execute comand "STRING lol" when  I focused on this text area, Rucky input "lo" and press Super button (The same of Windows button)
And when my phone with Rucky connected to computer my computer keyboard work  strange too. I installed Rucky from official NetHunter store.

**Comment by mayankmetha** [comment]
Hey, thanks for reporting the issue. I wasn't able to reproduce the bug. May I know which windows/linux version you are using and which keyboard layout.

**Comment by SM-py** [comment]
I have Kali Linux 2020.2, and my keyboard has English and Russian layout, and i tested them all.

**Comment by SM-py** [comment]
I am tried install Rucky ver 2.0 instead version from NetHunter repositories, that have got same error. I am about to try it on Windows 10 and another computer with Windows 10.

**Comment by SM-py** [comment]
P.S. On Windows 10 all works perfect

**Comment by SM-py** [comment]
I can close an issue, but remmember this problem on Kali Linux

**Comment by mayankmetha** [comment]
Unable to reproduce this on Kali Linux 2019.x/2020.x, Ubuntu, Arch, Fedora, Windows 10 & MacOS.
