### ISSUE TITLE
Can't STRING $

### ISSUE THREAD

**Issue by Nour833** [mayankmetha/Rucky#27]
When I type
STRING $test
The output is test
STRING  $
The output is 
I tried many times with different ways but can't write this symbol  "$" 
I need this for writing some commands in  powershell in windows and many more things .

And thanks for your support in advance  <3

**Comment by mayankmetha** [comment]
`STRING SHIFT 4` can be used for $ 
In US English keyboard $ is mapped to SHIFT 4.

**Comment by mayankmetha** [comment]
In US English keyboard $ is mapped to SHIFT+4.
So STRING $ will display $.
Tested on Nexus 5 with Android 6 + NetHunter. So not able to reproduce the issue

**Comment by Nour833** [comment]
I test SHIFT 4 and it works for american keyboard
but please why when I type string $   doesn't work because I need it for french keyboard and in french keyboard there is botton named $ 
and thanks a lot for your speed support bro ;)

**Comment by mayankmetha** [comment]
Right Brace key ']' of US English is equivalent key for French '$' key.
