### ISSUE TITLE
Stopping

### ISSUE THREAD

**Issue by Nour833** [mayankmetha/Rucky#28]
Hi 
When I restart my phone or boot it a message  appear say "Rucky has been stopped "
Is this an error that can be fixed or no ?
And thanks in advance ❤

Galaxy s5 klte touchwiz 6 android 6.0.1

**Comment by mayankmetha** [comment]
Not sure if this is due to the rom used. Stock android 6 (Nexus 5) doesn't reproduce this issue. Can you provide me with the crash logs?

**Comment by Nour833** [comment]
Yes but how can I do this

**Comment by mayankmetha** [comment]
1) Reproduce the issue that you’re seeing.
2) After reproducing the issue, go into the main Settings app and select Developer Options.
3) Tap Take bug report (you may need to toggle the “On" switch at the top first). After a few minutes you will receive a prompt.

**Comment by Nour833** [comment]
Srry
But my phone is unable to detect the bug
I think that this error happen because I connect an usb to charge my phone and Rucky automatically run the scrip so I think this is the reason. 
If you want close the issue or wait until I discover a method to capture the bug .

**Comment by mayankmetha** [comment]
Maybe the ROM has a non standard implementation of some system features that is causing the issue. AOSP code doesn't show this issue yet.
