### ISSUE TITLE
Stuck on android 10

### ISSUE THREAD

**Issue by Shubhamvis98** [mayankmetha/Rucky#29]
almost every time, it stucks when starting and also after the play button pressed
and if you don't mind I want to know why you've added permission for GPS???

thanks for the great application

**Comment by mayankmetha** [comment]
Can you explain the stuck issue in detail.

GPS is used by network protocol to locate raspberry pi. Android doesn't categorically place some network protocols like mDNS/Bonjour in network permissions but under GPS permissions.

**Comment by Shubhamvis98** [comment]
It stuck because of GPS permission
When I enable it then it works well

But I noticed one more issue that once I opened the keyboard for typing, then it won't close using the back key
When I press the back key multiple times then the keyboard closes or I have to press the recent key then return to Rucky to close the keyboard

And if you can then please decrease the font size in the next release

Thanks...

**Comment by Shubhamvis98** [comment]
![Screenshot_20201109-150857_Rucky](https://user-images.githubusercontent.com/43336210/98524812-a8ac3500-229d-11eb-80ce-a41caf0ac702.png)
Stuck when opening

**Comment by mayankmetha** [comment]
Unable to reproduce the issue. Maybe this is related to a specific ROM.
