### ISSUE TITLE
Kernel isn't supported

### ISSUE THREAD

**Issue by Loki029** [mayankmetha/Rucky#3]
![Screenshot_20190828-153424_Device Control](https://user-images.githubusercontent.com/54595182/63860509-8fc1a780-c9a9-11e9-8cfc-f531d463e7fe.jpg)

Sorry if I open a New Issue, but I checked my kernel and it should work ??? I just simply accepted the fact that Rucky isn't compatible, but it should be? I'm really confused by now ¯\_(ツ)_/¯

In Kind Regards

**Comment by mayankmetha** [comment]
You need a custom kernel to work. Preferably use kali nethunter supported kernel for your device/rom.
