### ISSUE TITLE
Crash after crash

### ISSUE THREAD

**Issue by wujekbefore** [mayankmetha/Rucky#31]
Phone: Nexus 5x
NetHunter: 2020.4
Kernel: 3.10.73-Re3son-3.5

After downloading Rucky from NetHunterStore it keeps crashing. 
Crash also occurs when I download the .apk file from github.
Reinstallation does not work.

**Comment by mayankmetha** [comment]
Can you collect and share the bug report.

**Comment by wujekbefore** [comment]
> Can you collect and share the bug report.

https://pastebin.com/0vU8aa74

**Comment by mayankmetha** [comment]
Have you provided all the permissions asked for? 

Alternate solution is to use version 1.9 and ignore the update notification/alerts.

**Comment by wujekbefore** [comment]
> Have you provided all the permissions asked for?
> 
> Alternate solution is to use version 1.9 (available in the GitHub release page) and ignore the update notification/alerts.


Yes, I allowed all permission messages.
Ok, now I will try to install version 1.9

**Comment by wujekbefore** [comment]
> Have you provided all the permissions asked for?
> 
> Alternate solution is to use version 1.9 (available in the GitHub release page) and ignore the update notification/alerts.

The application version 1.9 works, unfortunately it does not fulfill its task. After entering a simple payload and pressing "play", nothing happens when the phone is connected to the computer. All permissions are allowed.


Payload:

DELAY 3000
GUI r
DELAY 500
STRING notepad
DELAY 500
ENTER
DELAY 750
STRING Hello World!
ENTER

**Comment by wujekbefore** [comment]
> Have you provided all the permissions asked for?
> 
> Alternate solution is to use version 1.9 (available in the GitHub release page) and ignore the update notification/alerts.


Ok it worked after selecting the "Use device as MIDI" option instead of "Only charging the phone".
Is it possible for this option to be automatically selected after connecting the phone to the computer?

**Comment by mayankmetha** [comment]
> > Have you provided all the permissions asked for?
> > Alternate solution is to use version 1.9 (available in the GitHub release page) and ignore the update notification/alerts.
> 
> Ok it worked after selecting the "Use device as MIDI" option instead of "Only charging the phone".
> Is it possible for this option to be automatically selected after connecting the phone to the computer?

As of now, no we cannot change the USB option type. Use NetHunter app to change the settings or use the stock android USB option notification.

**Comment by wujekbefore** [comment]
> > > Have you provided all the permissions asked for?
> > > Alternate solution is to use version 1.9 (available in the GitHub release page) and ignore the update notification/alerts.
> > 
> > 
> > Ok it worked after selecting the "Use device as MIDI" option instead of "Only charging the phone".
> > Is it possible for this option to be automatically selected after connecting the phone to the computer?
> 
> As of now, no we cannot change the USB option type. Use NetHunter app to change the settings or use the stock android USB option notification.


Thanks for your help and best regards. Great job!
