### ISSUE TITLE
Rucky will not install

### ISSUE THREAD

**Issue by markmn123** [mayankmetha/Rucky#32]
Phone: Oneplus 8 Pro
Android version 11
Build: Oxygen OS 11.0.2.2.IN11AA
Kernel version: 4.19.110-perf+

I had rucky installed on Oxygen OS 10.5.12 and working great (thanks by the way)
I did an OTA to 11.0.2.2 and then Rucky disappeared
when trying to redownload from NH store I get "Failed  to install due to unknown error"
when installing the apk directlyi click install, a bar appears for a half a second then it says "app not installed"

i factory reset my phone on 11.0.2.2 and installed kali chroot from scratch, tried installing rucky again and still same error
is there a way i can see the install log to find out what is happening?
I know android 11 is pretty fresh so there may not be much support but i just really didnt want to have to downgrade to 10 again.

**Comment by mayankmetha** [comment]
Try installing version 1.9 and check. Version 2.0 is having some issues with oxygenOS11.
