### ISSUE TITLE
Feature request: auto-apply configfs

### ISSUE THREAD

**Issue by Kuuhhl** [mayankmetha/Rucky#35]
To use this tool, a custom kernel is needed. 
However, in [this](https://github.com/pelya/android-keyboard-gadget) repository, I found that it is possible to replace this kernel patch by using configfs if the kernel is newer than 3.19.
That's why [USB Gadget Tool](https://github.com/tejado/android-usb-gadget) allows me to add the USB device and use Rucky without manually patching my kernel.

My suggestion would be to add an option to automatically apply this configfs patch before executing the script. 
An example would be a similar project, [Android USB Script](https://github.com/Netdex/android-usb-script). Their tool automatically uses configfs if no kernel patch is detected.

**Comment by RoopakParashar** [comment]
Thank you for your reply

**Comment by mayankmetha** [comment]
Adding this feature to next nightly update, and one verified it works as expected, it will be released in next release version as well. If you like to test it please switch to latest nightly release and wait for update to be pushed soon.
