### ISSUE TITLE
rucky works but doesn't execute anything

### ISSUE THREAD

**Issue by theRealCooller** [mayankmetha/Rucky#36]
Hi,

Using android 10, custom ROM. Rucky as an app works fine, in the tweaks tab it also shows 'USB Connected'. Root permission granted but does nothing.

Whenever I enter the ducky script and run it with the play button, the system just tells me it was granted superuser rights but it does nothing at all. No error or any feedback from the app nor the target pc, it doesn't even run the first line, which in this case is just open windows run menu. To me, it seems working fine but pc doesn't recognize my phone as a keyboard or something. What am I doing wrong?

thanks for any help

using the latest app version, downloaded from [your releases](https://github.com/mayankmetha/Rucky/releases/tag/2.1)
**device:** xiaomi mi 9t pro
**os version:** 17.1.20200411-unofficial-raphael
**kernel:** 4.14.117.perf-g3e05af5 

**This simple script I'm trying to run:**
DELAY 3000
GUI r
DELAY 500
STRING notepad
DELAY 500
ENTER
DELAY 750
STRING Hello World!!!
ENTER

**Comment by mayankmetha** [comment]
Are you using a supported kernel of a configfs settings from external app?

**Comment by theRealCooller** [comment]
> 
> 
> Are you using a supported kernel of a configfs settings from external app?

I just did it, with [gadged-tools](https://github.com/tejado/android-usb-gadget), it all works flawlessly now, any chance to get support for Czech keyboard layout?  amazing work man... 

offtopic q: do you know where to find some basic payloads? would be nice to see what people can do with it, but what I found so far is mostly outdated
