### ISSUE TITLE
Hey I can't use rucky

### ISSUE THREAD

**Issue by Zeel2323-coder** [mayankmetha/Rucky#37]
I have lenovo k8 plus phone. 
With android 8.
This apk is installed but when I open this it freeze.
What I can do.??

**Comment by mayankmetha** [comment]
Is it the latest version of the app? 

Maybe device is not rooted or maybe kernel is not supported. 

If it is OEM ROM, then some OEM specific customisation can cause such issues.

**Comment by mayankmetha** [comment]
Didn't get the details asked.
