### ISSUE TITLE
Disable usb conmection detection

### ISSUE THREAD

**Issue by TQMatvey** [mayankmetha/Rucky#39]
i have rooted S21 Ultra and with USB Gadget tool rucky 1.9 works perfectly and rucky 2.0, 2.1 doesnt detect any cable or so, i tested everythink and still doesnt do anything

**Comment by TQMatvey** [comment]
is it possible to remove usb cable detection in next versions? as i really like it and would like to use 2.1 or 2.2 when it comes out

**Comment by mayankmetha** [comment]
You can disable the usb option in the settings and it will revert to the same functionality as older versions.

**Comment by TQMatvey** [comment]
if it is the usb connect Launch, i enabled it and it doesnt give me error but also doesnt run on pc :v

**Comment by TQMatvey** [comment]
i tested like everything and i dont rlly see disable usb option

**Comment by mayankmetha** [comment]
Complete usb cable detection is not possible. But turning off that in settings reverts back to usb feature from version 1.9. When the settings is turned off, usb detection will not hinder the rubber duck script launching action.

**Comment by mayankmetha** [comment]
Moreover usb gadget tool makes use of configFS. Make sure that kernel supports and enables configFS and the options are set correctly for hid keyboard. 
For this app to work, still you will require /dev/hidg0 as keyboard and the device needs to be rooted.

**Comment by mayankmetha** [comment]
If still none of these work, I assume it may be the ROM implementation that is causing the issue. I have tested on AOSP and OxygenOS based ROMs and it works fine.

**Comment by TQMatvey** [comment]
well i have supported kernel and everything i will probs stick to 1.9 as 2.1 still doesnt work
