### ISSUE TITLE
Rucky unable to use Network socket attack

### ISSUE THREAD

**Issue by Decapitater** [mayankmetha/Rucky#42]
Hi 
I'm unable to use the network socket attack. My Kernel is supported and usb attack works fine
I have tried several ports 22,443,80.
The Network socket showed connected in all 3 cases but i was unable to execute the script after pressing the run button
I tried rndis in Usb arsenal to make it work 
i tried different devices including android 
I used hello world script
the built in nethunter HID works and Duckhunter too 
Wifi injection is not working if that effects the situation

**Comment by mayankmetha** [comment]
For network socket, you would have to develop the socket server to receive the USB hid commands. This is not same as wifi injection. This was designed to keep in mind the raspberry pi 0w and similar devices in mind that can extend this apps capabilities.

**Comment by mayankmetha** [comment]
The network socket server is open for implementation with end users innovation with 2 basics requirements. Server will act like a USB hid (redirect command to hid USB device files /dev/hidg0). Server needs to support apps side heartbeat messages.

**Comment by Decapitater** [comment]
Oh I get it now it's like remote detonate for rasberry wifi duck 
Thanks for responding this fast
Does it support official wifi duck by dstrike
