### ISSUE TITLE
F11=F1

### ISSUE THREAD

**Issue by david67kill** [mayankmetha/Rucky#44]
I tried to run a simple script that display a fake update screen on windows using the default browser:

GUI r
DELAY 500
STRING chrome -k http://fakeupdate.net/win10ue/
ENTER
F11

But instead of pressing f11 and going full screen, the computer detected f1 and opened the help page of the browser.

**Comment by mayankmetha** [comment]
Hi,

Fix has been added to Nightly Release v425. Please check [README](https://mayankmetha.github.io/rucky) for more details. 

Thanks for showing a bug. It helps improve the app. :-)
