### ISSUE TITLE
Automatic launch attack on USB connection

### ISSUE THREAD

**Issue by tuphr1928** [mayankmetha/Rucky#49]
USB Connect Launch is turned on but I don't understand how to make it actually launch the attack without me pressing a button.
I couldn't find an answer anywhere over the web. Help please?

**Comment by mayankmetha** [comment]
When using automatic mode:
- USB cable is not connected: If you click run button, the scripts is prepared for execution but will wait for usb connection to happen to launch.
- When usb cable is connected: If you click run button, the script will execute.
- Run button click is required, as there is no way to determine when to execute the script.
