### ISSUE TITLE
Feature Request: Encrypted scripts

### ISSUE THREAD

**Issue by WuerfelDev** [mayankmetha/Rucky#5]
I want to send username and password to my computer to login, but I dont want this script stored in plaintext. It would be useful if I can save a script encrypted and when loading it from storage I have to "unlock" it with a password.
This will be useful for any kind of sensitive scripts

**Comment by mayankmetha** [comment]
Thanks for this idea. I was working on encrypted storage of scripts for the next release.

**Comment by mayankmetha** [comment]
Featuring in v1.8 release.
