### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by mato200** [mayankmetha/Rucky#51]
I think that the app is not working using this method of HID : https://github.com/tejado/android-usb-gadget
Could you please make it work.
I know my phone is possible of HID input because it works with https://github.com/tejado/Authorizer app
I can also send inputs using this (explained here https://github.com/tejado/android-usb-gadget)
"cd /data/local/tmp
# Send letter 'a'
echo a | ./hid-gadget-test /dev/hidg0 keyboard
"

I can also do everything this guy does here https://www.youtube.com/watch?v=Mek9DMGy8os (time 6:23)

Phone: Redmi K20 Pro (MIUI 12)(Android 11)

**Comment by mayankmetha** [comment]
Shell script won't work, please use duck scripts. 

Example to send letter 'a'

STRING a
