### ISSUE TITLE
STRING_DELAY support

### ISSUE THREAD

**Issue by H3XDaemon** [mayankmetha/Rucky#53]
https://github.com/hak5darren/USB-Rubber-Ducky/issues/26
Just got random string uppercase on Redhat Linux 8
I tested with digispark no such issue
Windows and Android either
Maybe just string input too fast

**Comment by mayankmetha** [comment]
Did you have tried the command DEFAULT_DELAY?
Just put it at the begin of your script
DEFAULT_DELAY 1000
Now there is a delay of 1000 ms between each command.
If there is a DELAY command anywhere after that in the script it should override the delay between the previous command and the next command

STRINGDELAY is still broken on original ducky scripts. I suggest using DELAY

**Comment by H3XDaemon** [comment]
Yes, I tried it, and it seems that I can only delay it with one word per line

**Comment by mayankmetha** [comment]
Feature added. Next nightly release to feature this.

**Comment by H3XDaemon** [comment]
Thank you so much

**Comment by mayankmetha** [comment]
Rucky v2.3 and Rucky Nightly 476 supports this.
