### ISSUE TITLE
Can`t type a '+' using german Layout

### ISSUE THREAD

**Issue by S1910239021** [mayankmetha/Rucky#54]
When using STRING + the output is '4'.

I`m working with a OnePlus7 PRO, Android 10 and App Version 2.1.

**Comment by S1910239021** [comment]
SHIFT + should be a * but is  a `

**Comment by mayankmetha** [comment]
Try with latest version v2.2.

**Comment by S1910239021** [comment]
Thanks.

But sorry. It's still the same in Version 2.2.
The output of "STRING +" is '4'

**Comment by mayankmetha** [comment]
Try the latest nightly. First uninstall Version 2.2 Then install Nightly 473. https://raw.githubusercontent.com/mayankmetha/Rucky/master/nightly/rucky-nightly.apk
