### ISSUE TITLE
Suggestion: fix battery optimization

### ISSUE THREAD

**Issue by zalexdev** [mayankmetha/Rucky#57]
Hi with this command you can prevent basic battery optimization!
`su -c "dumpsys deviceidle whitelist +com.app.package"`

**Comment by mayankmetha** [comment]
What do we want to achieve with battery optimisation bypass? What is the feature that is blocked if this is not enabled?

**Comment by mayankmetha** [comment]
Battery optimisation bypass does not seem to be required at this moment as battery utilisation of the app is low.
