### ISSUE TITLE
ALT SHIFT doesn't work

### ISSUE THREAD

**Issue by xekebet62** [mayankmetha/Rucky#6]
I have  Russian language default in my computer. For the script to work, need to switch language in English by pressing "ALT+SHIFT". The Rucky can't do this. I tried "ALT SHIFT","ALT-SHIFT", "ALT shift", "Alt-shift", "ALT+SHIFT", etc... It doesn't work. "GUI r" works good, but "ALT Shift" doesn't. The script is:

DELAY 3000
ALT SHIFT
DELAY 500
GUI r
DELAY 500
STRING iexplore -k http://fakeupdate.net/win10u/index.html
ENTER
DELAY 100
ALT SHIFT

Sorry for my bad English.

**Comment by mayankmetha** [comment]
ALT SHIFT isn’t a valid rubber duck script sequence as defined by Hak5. Refer this like for list of valid command sequence. https://docs.hak5.org/hc/en-us/articles/360010555153-Ducky-Script-the-USB-Rubber-Ducky-language

**Comment by xekebet62** [comment]
I was looking for a solution and found it:
https://forums.hak5.org/topic/40219-question-how-to-script-to-change-device-language-using-altshift/
https://github.com/hak5darren/USB-Rubber-Ducky/blob/master/Encoder/README
But it does not work with Rucky. How can I do solve the problem? Please halp.
Sorry for my bad English.

**Comment by mayankmetha** [comment]
This option will be added in the next release only.

**Comment by xekebet62** [comment]
How about adding option, which will rename or delete saved script from "Saved scripts list" (Select file) in next release, too?

**Comment by xekebet62** [comment]
> Save/Load will be from the existing Directory only and would not change due to back compactability issue of newer Android API with older android versions.

How about rename and delete? Could it be?

**Comment by mayankmetha** [comment]
> > This option will be added in the next release only.
> 
> I hope the author will fulfill the promise as soon as possible.

Only in the next release it will be there.
Currently Im held up with few other projects 
As soon as I get some time Ill finish the update release and push it.

**Comment by mayankmetha** [comment]
Code changes done.
