### ISSUE TITLE
Support for various keyboard mapping

### ISSUE THREAD

**Issue by anduril-glitch** [mayankmetha/Rucky#7]
Hello, I would have liked to know if it was possible to put the application in azerty because it poses problem at home, being in azerty.

**Comment by mayankmetha** [comment]
is azerty French keyboard layout?

**Comment by anduril-glitch** [comment]
Yes

**Comment by anduril-glitch** [comment]
I tried to switch my phone's keyboard to qwerty but it doesn't work. When I type in qwerty it types in azerty on the computer and in azerty it is the reverse. I don't understand it. Do you have an idea to solve the problem?

**Comment by mayankmetha** [comment]
I’m not sure why that’s happening. I’m rewriting the keyboard logic for the next release to support various keyboard formats.

**Comment by mayankmetha** [comment]
Added French keyboard layout. Will be featured in next release. Check back in a few days for the new release at https://github.com/mayankmetha/Rucky/releases/latest
