### ISSUE TITLE
Need help: Typing in a different language

### ISSUE THREAD

**Issue by Jeagtso** [mayankmetha/Rucky#72]
I want to be able to make the script type in different language (non-English)
I want to to be able to type in arabic, willing to help with the code, just need to know how to add it and I'll do the work.

**Comment by mayankmetha** [comment]
You can create a HID mapping for the langauage you want and also submit the HID mapping json file as well. In the app you can make use of the customise HID option under settings and create new langauage mapping and add indivual key mapping which will create the json file for you. 

Link for existing mapping:
https://github.com/mayankmetha/Rucky-KeyMap

**Comment by Jeagtso** [comment]
will do and share the json file.

**Comment by Jeagtso** [comment]
[arabic.zip](https://github.com/mayankmetha/Rucky/files/8205726/arabic.zip)
I faced few issues, every time I tried to edit the json file through the app, to add a new letter for example, it'd delete all other added letters (to be precise "deleting" isn't accurate, it just removed their unicodes and only saves the latest letter unicode) , or when I tried to edit a key it would just create a new copy instead of replacing it.
and  sometimes when I try to open the menu to change the language (the button next to run button), the app would just crash.

I had to make the json file on PC because it was impossible to do it otherwise.

**Comment by mayankmetha** [comment]
Maybe you can manually follow the other repo's json structure and create a json file and use it.

**Comment by Jeagtso** [comment]
That's what I did, you can find it in the ZIP file I uploaded,
I was just reporting the few issues I faced within the app,
But other than that everything was fine

**Comment by YVS37** [comment]
U
