### ISSUE TITLE
Kernel not supported 

### ISSUE THREAD

**Issue by anduril-glitch** [mayankmetha/Rucky#8]
Hello,
Would it be possible to make the application compatible with my kernel?
Thank you
A [+]

[https://zupimages.net/viewer.php?id=19/52/5ytx.png](url)

**Comment by mayankmetha** [comment]
Kernels with usb his gadgets where keyboard is hidg0 and mouse is hidg1 are supported. No other kernel is supported as I can’t verify the application execution process.

**Comment by skluthe** [comment]
I'm getting kernel not supported on my Nexus 5 running nethunteros. Are there any logs I can give you to figure out why it's popping up?

**Comment by mayankmetha** [comment]
Kernel does not have hid interface/device files hence it isn’t supported. NethunterOS isn’t supported as it’s a unsupported project. Only the Android Kali Linux NetHunter Builds on their website for nexus 5 is supported.

**Comment by skluthe** [comment]
The one located here:
https://www.offensive-security.com/kali-linux-nethunter-download ?
Is there a preferred ROM to go with this?

**Comment by anduril-glitch** [comment]
I installed "LOS-hammerhead-14.1-20170102-nethunteros" with kali-fs in the chroot is Rucky works great.

**Comment by skluthe** [comment]
I'll try that out. Thanks!

**Comment by skluthe** [comment]
> I installed "LOS-hammerhead-14.1-20170102-nethunteros" with kali-fs in the chroot is Rucky works great.

Just tried it and I'm getting the same error. Are you sure you don't have another kernel installed?

**Comment by anduril-glitch** [comment]
At home it works thunder with the kernel, I even tried without kali-fs

**Comment by anduril-glitch** [comment]
There are 3 in hammerhead, try the 3

**Comment by mayankmetha** [comment]
Easiest one is install the last rom by google for nexus 5. Root it using Magisk and then install the kali Linux NetHunter package from https://www.offensive-security.com/kali-linux-nethunter-download @skluthe

**Comment by mayankmetha** [comment]
You need custom kernel to make it work @skluthe, the nethunter package from the above link has the necessary kernel included. I use this method. Another one is find the last release of LOS14.1 and then build and flash the kernel from my git repo https://github.com/mayankmetha/Nethunter-Hammerhead-Kernel (a bit messy work).

**Comment by skluthe** [comment]
Solution: used nethunteros-nethunter-hammerhead-cm-14.1-hammerh.zip from
build.nethunter.com.

Flashed kernel-nethunter-hammerheadmon-nougat-2019.03-13-0514.zip from
build.nethunter.com.

Setup the latest kalifs (armhf full version) opened androidsu shell, typed
in setprop sys.usb.config hid and then I was able to use Ricky.

**Comment by mayankmetha** [comment]
> Solution: used nethunteros-nethunter-hammerhead-cm-14.1-hammerh.zip from build.nethunter.com. Flashed kernel-nethunter-hammerheadmon-nougat-2019.03-13-0514.zip from build.nethunter.com. Setup the latest kalifs (armhf full version) opened androidsu shell, typed in setprop sys.usb.config hid and then I was able to use Rucky.

Nice work. Hope this solution will benefit others also. 🙂
