### ISSUE TITLE
Where are the scripts stored on the phone?

### ISSUE THREAD

**Issue by anduril-glitch** [mayankmetha/Rucky#9]
Good evening,

I would have liked to know where the scripts were stored on the phone?

Is there the possibility to choose the location manually?

Thank you

A +

**Comment by mayankmetha** [comment]
Currently file locations cannot be selected. I let it be in the default app location provided by android for each app, so it becomes easier to clean up the junk when app is uninstalled without any additional overhead code. Android itself will do the cleanup on uninstalling the app.
