### ISSUE TITLE
virtual environment in not supported

### ISSUE THREAD

**Issue by ekko95** [mayankmetha/Rucky#91]
I have installed and tried to run Rucky but every time I run it a box shows up saying "virtual environment in not supported!" is there anyway to fix this or am I not able to use it? (I'm using a rooted google pixel 5)

**Comment by mayankmetha** [comment]
Seems like your rom properties has one of the following details which is causing it be detected as an emulator:

`(Build.BRAND.startsWith("generic") && Build.DEVICE.startsWith("generic"))
                || Build.BOARD.contains("unknown")
                || Build.FINGERPRINT.startsWith("generic")
                || Build.FINGERPRINT.startsWith("unknown")
                || Build.HARDWARE.contains("goldfish")
                || Build.HARDWARE.contains("ranchu")
                || Build.ID.contains("FRF91")
                || Build.MODEL.contains("google_sdk")
                || Build.MODEL.contains("Emulator")
                || Build.MODEL.contains("Android SDK built for x86")
                || Build.MODEL.contains("sdk")
                || Build.MANUFACTURER.contains("unknown")
                || Build.MANUFACTURER.contains("Genymotion")
                || Build.PRODUCT.contains("sdk_google")
                || Build.PRODUCT.contains("google_sdk")
                || Build.PRODUCT.contains("sdk")
                || Build.PRODUCT.contains("sdk_x86")
                || Build.PRODUCT.contains("vbox86p")
                || Build.PRODUCT.contains("emulator")
                || Build.PRODUCT.contains("simulator")
                || Build.USER.contains("android-build")`

**Comment by srt54558** [comment]
> Seems like your rom properties has one of the following details which is causing it be detected as an emulator:
> 
> `(Build.BRAND.startsWith("generic") && Build.DEVICE.startsWith("generic"))
>                 || Build.BOARD.contains("unknown")
>                 || Build.FINGERPRINT.startsWith("generic")
>                 || Build.FINGERPRINT.startsWith("unknown")
>                 || Build.HARDWARE.contains("goldfish")
>                 || Build.HARDWARE.contains("ranchu")
>                 || Build.ID.contains("FRF91")
>                 || Build.MODEL.contains("google_sdk")
>                 || Build.MODEL.contains("Emulator")
>                 || Build.MODEL.contains("Android SDK built for x86")
>                 || Build.MODEL.contains("sdk")
>                 || Build.MANUFACTURER.contains("unknown")
>                 || Build.MANUFACTURER.contains("Genymotion")
>                 || Build.PRODUCT.contains("sdk_google")
>                 || Build.PRODUCT.contains("google_sdk")
>                 || Build.PRODUCT.contains("sdk")
>                 || Build.PRODUCT.contains("sdk_x86")
>                 || Build.PRODUCT.contains("vbox86p")
>                 || Build.PRODUCT.contains("emulator")
>                 || Build.PRODUCT.contains("simulator")
>                 || Build.USER.contains("android-build")`

Can you make it possible to ignore that popup? I can't launch the app on my Pixel 8 Pro (December patch/stock software/rooted). Version 1.9 works flawlessly
